# Generated by Django 5.0.7 on 2024-07-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionoptions',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='subscriptionoptions',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
