# Generated by Django 5.0.7 on 2024-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoptions',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
