# Generated by Django 5.0.7 on 2024-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignedPeople',
            fields=[
                ('id_user', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('subscription', models.CharField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('update_up', models.DateTimeField(auto_now=True)),
                ('create_up', models.DateTimeField(auto_now_add=True)),
                ('action_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
