# Generated by Django 5.0.7 on 2024-08-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signedpeople',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
