# Generated by Django 5.0.7 on 2024-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DissatisfiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.CharField()),
                ('user_name', models.CharField()),
                ('question_user', models.TextField()),
                ('create_up', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
