# Generated by Django 5.0.7 on 2024-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_temporarydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarydata',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
