# Generated by Django 5.0.7 on 2024-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_temporarydata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarydata',
            name='id',
        ),
        migrations.AddField(
            model_name='temporarydata',
            name='file_unique_id',
            field=models.CharField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
